### ISSUE TITLE
Don't work with Y.A.R.D.2

### ISSUE THREAD

**Issue by Niklas04** [b-jesch/service.pvr.manager#6]
Hi,
my goal was to wakeup my Raspberry Pi 3 B+ running LibreELEC for a scheduled recording.
So I purchased a Y.A.R.D.2 . 

A scheduled wakeup with the Y.A.R.D.2 works fine - but the wakeup with PVR Recording & Power Manager won't work. I have been looking in the code for the error and found it:

1.  In my opinion in line 20 of the shutdown.sh-file the parameter is wrong
Instead of a small L it should be a big i
In the [manual](https://www.yard2usb.de/files/YARD2_Manual.pdf) of the Y.A.R.D.2 there is no (small) L-Parameter for the yard2wakeup-function (see page 37)
2. The  yard2wakeup-function has to be called with its entire path. According to the Y.A.R.D.2-Manual (page 43) the Y.A.R.D2-Software should be located in the path " /storage/yard2"

Line 20 of shutdown.sh should be:
storage/yard2/yard2wakeup -I $1

I tested the changes on my system and it works fine

Best regards
Niklas

**Comment by b-jesch** [comment]
Hello Niklas

The Issue with false Option (I instead l) has been fixed. Because the install path of yard2 may different on other systems I have a notice included in the README. The best way is include a PATH extension into the .profile file to point the installation folder of yard2 -even in *Elec systems.

Regards
Birger

**Comment by danneboom** [comment]
Hey @Niklas04 , could you please add some information on how to use a yard2 on a raspberry pi? How did you connect it, just USB or do you use some GPIO pins as well?
